In [1]:
import pandas as pd
import numpy as np

In [2]:
pwd

'/Users/Work/Documents/Predicting-Neighborhood-Affluence-with-Yelp/Code'

In [85]:
df = pd.read_csv('/Users/Work/Downloads/2019_Registered_Foreclosure_Properties.csv')

In [86]:
df

,APN,Registered Date,Property Type,Property Address,Property City,Property State,Property Zip,Council District,Lender,Lender Contact,...,Property Management Contact Phone,Longitude,Latitude,Property on Map,Zip Codes,Census Tracts,Precinct Boundaries,LA Specific Plans,Council Districts,Neighborhood Councils (Certified)
0,2403008013,08/09/2019,Non-Residential,0,NaN,CA,0,2,"MJS Enterprise, Inc.",John Arbucci,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5223009003,01/25/2019,Vacant Residential,2008 N MARIANNA AVE,LOS ANGELES,CA,90032,14,"Cardenas Three, LLC",Elizabeth Velasquez,...,NaN,-118.17744,34.06631,POINT (-118.17744 34.06631),23449.0,507.0,616.0,NaN,9.0,91.0
2,2163022043,08/27/2019,Single Family,5353 N DONNA AVE,LOS ANGELES,CA,91356,3,"Danco, Inc.",Ronald Perlstein,...,NaN,-118.54861,34.16858,POINT (-118.54861000000001 34.16858),19339.0,321.0,1496.0,NaN,4.0,10.0
3,6075015011,01/02/2019,Single Family,612 W 111TH PL,LOS ANGELES,CA,90044,8,Vijay Fadia,Vijay Fadia,...,NaN,-118.28533,33.93375,POINT (-118.28533 33.93375),23675.0,814.0,1192.0,7.0,14.0,53.0
4,2425017001,01/14/2019,Non-Residential,0,NaN,CA,0,4,"MUFG Union Bank, N.A.",Domar Aledia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999,2551023041,01/03/2019,Single Family,11054 N ELDORA AVE,LOS ANGELES,CA,91040,7,Arvest Central Mortgage Company,Gerald Brown,...,877-339-8202,-118.31421,34.27027,POINT (-118.31421 34.27027),3221.0,11.0,529.0,NaN,1.0,7.0
3000,2530022081,01/02/2019,Single Family,11300 W FOOTHILL BLVD,LOS ANGELES,CA,91342,7,M&T Bank,Eric Moore,...,877-338-3791,-118.37675,34.27556,POINT (-118.37675000000002 34.27556),18912.0,19.0,1087.0,8.0,1.0,9.0
3001,2510020035,01/02/2019,Single Family,13463 W HUBBARD ST,LOS ANGELES,CA,91342,7,"Trustee Corps, Bayview Loan Servicing",Madeline DeFranco,...,800-852-8306,-118.42680,34.31088,POINT (-118.4268 34.31088),18912.0,41.0,289.0,NaN,1.0,47.0
3002,7562022027,09/19/2019,Single Family,2128 W MCRAE DR,SAN PEDRO,CA,90732,15,BANK OF AMERICA,VPR DEPARTMENT,...,818-406-3611,-118.32172,33.72679,POINT (-118.32172 33.72679),3343.0,984.0,1454.0,NaN,15.0,33.0
3003,4327004003,01/07/2019,Single Family,1416 S PANDORA AVE,LOS ANGELES,CA,90024,5,bayview,Willie Walton,...,213-804-7437,-118.42630,34.06135,POINT (-118.42629999999998 34.06135),23442.0,858.0,501.0,9.0,6.0,72.0

In [87]:
df.isna().sum()

APN                                     0
Registered Date                         0
Property Type                           0
Property Address                        0
Property City                           5
Property State                          0
Property Zip                            0
Council District                        0
Lender                                  0
Lender Contact                          0
Lender Contact Phone                    0
Property Management                   125
Property Management Contact           121
Property Management Address           121
Property Management Contact Phone     121
Longitude                               5
Latitude                                5
Property on Map                         5
Zip Codes                               5
Census Tracts                           6
Precinct Boundaries                     5
LA Specific Plans                    1954
Council Districts                       8
Neighborhood Councils (Certified)     118
dtype: int64

In [88]:
df.shape

(3004, 24)

In [91]:
foreclosed_sum_zips = pd.DataFrame(df['Property Zip'].value_counts())
foreclosed_sum_zips = foreclosed_sum_zips.reset_index().rename(columns={'index':'zip_code'})
foreclosed_sum_zips = foreclosed_sum_zips.rename(columns={'Property Zip':'foreclosed_count'})
foreclosed_sum_zips.head()

   zip_code  foreclosed_count
0     91331               111
1     91342               107
2     90047                98
3     91344                86
4     90044                81

In [92]:
# foreclosed_sum_zips.to_csv('/Users/Work/Desktop/foreclosed.csv', index=True)